# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pip:
    - rpaframework==28.0.0        # https://rpaframework.org/releasenotes.html
    - robocorp==1.4.0             # https://pypi.org/project/robocorp
    - robocorp-browser==2.2.1     # https://pypi.org/project/robocorp-browser
    - attrs==23.2.0
    - certifi==2024.2.2
    - et-xmlfile==1.1.0
    - exceptiongroup==1.2.0
    - h11==0.14.0
    - idna==3.7
    - openpyxl==3.1.2
    - outcome==1.3.0.post0
    - PySocks==1.7.1
    - python-dateutil==2.9.0.post0
    - selenium==4.15.2
    - six==1.16.0
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - trio==0.25.0
    - trio-websocket==0.11.1
    - typing_extensions==4.11.0
    - urllib3==2.2.1
    - wsproto==1.2.0
